[phases.setup]
nixPkgs = ["python39", "nodejs-20_x", "libgomp", "git"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt",
  "pip install -e ."
]

[phases.build]
cmds = ["echo 'Build completed'"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 300 --pythonpath examples stream_output_via_api:app"
